# Pandas Basic

## pandas languages:
- numpy - numerical data and mathmetical operations
- matplotlib - data visulation

In [44]:
import numpy as np 
import pandas as pd

In [45]:
print(f'Pandas: {pd.__version__}')
print(f'Numpy: {np.__version__}')

Pandas: 3.0.2
Numpy: 2.4.4

## pandas datastructures
- series - a single demisional datastructure. similar to a list
    - homogeneous (of the same dt)
- dataframe - multidimensional table
    - heterogenous

In [46]:
ser1 = pd.Series([10, 20, 30, 40], index=['A', 'B', 'C', 'D'])

print(ser1)

A    10
B    20
C    30
D    40
dtype: int64

In [47]:
d ={
    "b": 1,
    "a": 0,
    "c": 2,
    "d": 100
}

ser2 = pd.Series(d)

In [48]:
d1 = {
    "a": 0.0,
    "b": 1.0,
    "c": 2.0
}

ser3 = pd.Series(d1)

print(ser3)

a    0.0
b    1.0
c    2.0
dtype: float64

In [49]:
calories = {
    'day1': 700,
    'day2': 2500,
    'day3': 1200
}

ser4 = pd.Series(calories)

print(ser4)

day1     700
day2    2500
day3    1200
dtype: int64

In [50]:
ser5 = pd.Series(5.0, index=['a', 'b', 'c'])

print(ser5)

a    5.0
b    5.0
c    5.0
dtype: float64

## data frame:
- indexes (each number)
- columns (each variables)

In [51]:
fruitData = {
    'apple_sales': [3,2,0,2,9,4,7,2],
    'orange_sales': [0,3,2,7,7,8,3,0]
}

# idx = [2000, 2001, 2002, 2003, 2005, 2006, 2007, 2008]
idx = pd.RangeIndex(2000, 2008)

purchases = pd.DataFrame(fruitData, index=[idx])

print(purchases)

      apple_sales  orange_sales
2000            3             0
2001            2             3
2002            0             2
2003            2             7
2004            9             7
2005            4             8
2006            7             3
2007            2             0

In [52]:
rows, cols = purchases.shape

print(f'Rows: {rows}')
print(f'Cols: {cols}')

Rows: 8
Cols: 2

In [53]:
print(purchases.head())

      apple_sales  orange_sales
2000            3             0
2001            2             3
2002            0             2
2003            2             7
2004            9             7

In [54]:
purchases.tail()

      apple_sales  orange_sales
2003            2             7
2004            9             7
2005            4             8
2006            7             3
2007            2             0

## Importing files with pandas
- `.read_csv()`
- `.read_excel`

In [55]:
employee_df = pd.read_csv('pandasBasic\data\employee.csv')

employee_df.head()

<>:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
<>:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
C:\Users\devon\AppData\Local\Temp\ipykernel_12936\3981359950.py:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
  employee_df = pd.read_csv('pandasBasic\data\employee.csv')

      Name   Age  Weight     Salary
0    James  36.0    75.0  5428000.0
1  Villers  38.0    74.0  3428000.0
2    VKole  31.0    70.0  8428000.0
3    Smith  34.0    80.0  4428000.0
4    Gayle  40.0   100.0  4528000.0

In [56]:
rows, cols = employee_df.shape
print('Rows', rows)
print('Cols:', cols)

Rows 15
Cols: 4

In [57]:
employee_df.dtypes

Name          str
Age       float64
Weight    float64
Salary    float64
dtype: object

In [58]:
carsDf = pd.read_json('pandasBasic\data\cars.json')

carsDf.head()

<>:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
<>:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
C:\Users\devon\AppData\Local\Temp\ipykernel_12936\4159799006.py:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
  carsDf = pd.read_json('pandasBasic\data\cars.json')

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin,quantity,city
0,Chevrolet Vega,25.0,4,140.0,75,2542,17.0,74,US,177,NJ
1,Chevrolet Vega (sw),22.0,4,140.0,72,2408,19.0,71,US,91,DALLAS
2,Chevrolet Vega 2300,28.0,4,140.0,90,2264,15.5,71,US,74,TEXAS
3,Chevrolet Woody,24.5,4,98.0,60,2164,22.1,76,US,241,OH
4,Chevrolete Chevelle Malibu,16.0,6,250.0,105,3897,18.5,75,US,206,NewYork

In [59]:
rows, cols = carsDf.shape
print('Rows', rows)
print('Cols:', cols)

Rows 161
Cols: 11

In [60]:
carsDf.dtypes

Car                 str
MPG             float64
Cylinders         int64
Displacement    float64
Horsepower        int64
Weight            int64
Acceleration    float64
Model             int64
Origin              str
quantity          int64
city                str
dtype: object

## EDA - the first look (step 1 of data prepping)
- data profiling
    - structure(shape)
    - qaulity (missing vals, dups, unique vals)
    - content(data types, dispersion, measures central tendency)

- profiling tech
    - data type and format validation
    - statiscal summaries(descriptive stats, values counts, frequncy checks)
    - uniquness and cardinality
    - pattern recog
    - cross0validation